---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: analysis
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs:v1.0.0
    commands:
      - /root/entrypoint.sh
      - sbt -ivy ./.ivy2 dependencyCheck
      - sbt scalastyle | true
      - sbt scapegoat | true
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
      ENV_LOG_LEVEL: ERROR
    when:
      event:
        - push

  - name: sonar-scanner
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    commands:
      - sonar-scanner -Dsonar.projectVersion=B${DRONE_BUILD_NUMBER}
    environment:
      DRONE_BUILD_NUMBER: ${DRONE_BUILD_NUMBER}
    when:
      branch:
        - ${DRONE_BRANCH}
      event:
        - push
    depends_on:
      - analysis

  - name: build
    pull: if-not-exists
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt +publish
    environment:
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_USERNAME: drt-artifactory-robot
    when:
      branch:
        - ${DRONE_BRANCH}
      event:
        - push
...
